### ISSUE TITLE
Errors on Ubuntu with kernel 3.19.0-26

### ISSUE THREAD

**Issue by arty-name** [SWW13/hid-synaptics#5]
I have been using this module on Ubuntu 15.04 for quite some time without issues. However recently a new kernel 3.19.0-26 came in and I see a problem when using it. At boot time systemd hangs for 3 minutes while waiting for some service to come up. [Logs are filled with repeating strings `New USB device found, idVendor=0489, idProduct=e076` at that time](https://arty.name/journalctl.txt). Could you have a look, please?

**Comment by SWW13** [comment]
Hi, I had that working on a 4.0 and 4.1 kernel and there will a upstream fix in 4.3 (see http://www.spinics.net/lists/linux-input/msg40080.html).

I don't have an idea what the problem could be and as there is already an upstream fix ready I don't want to spent time on analyzing the problem, sorry for that.

**Comment by arty-name** [comment]
Fair enough. Too bad I couldn't get the system working with 4.0 and 4.1: if not the keyboard, then the intel video driver fails. 

Which distro do you use, btw?

**Comment by SWW13** [comment]
I'm using Arch Linux with a custom mainline kernel.

**Comment by arty-name** [comment]
You were right not to waste time on that. It was [an issue with ath3k firmware](https://bugs.launchpad.net/ubuntu/+source/linux-lts-utopic/+bug/1462614).
