### ISSUE TITLE
Fedora Error make

### ISSUE THREAD

**Issue by netzgestaltung** [SWW13/hid-synaptics#6]
hi,

i try to install your patch with fedora and get the following error when entering "make" as root:

```
[root@localhost hid-acer]# make
make -C /lib/modules/4.2.0-300.fc23.x86_64/build M=/home/<username>/Downloads/hid-acer-master/hid-acer modules
make[1]: *** /lid/modules/4.2.0-300.fc23.x86_64/build: Datei oder Verzeichnis nicht gefunden. Schluss.
Makefile:27: recipe for target 'default' failed
make: *** [default] Error 2
```

du you have any idea what is wrong? Is there any chance to make it work with fedora?

**Comment by SWW13** [comment]
Do you have dev tools and headers installed?
`dnf install kernel-devel kernel-headers`

You could also try to get a mainline kernel (4.3), this one should already contain an fix for the usage index exceeded problem.

**Comment by netzgestaltung** [comment]
yes, i did install them before - as adviced in the readme file. 
When will the new kernel aproximetly arrive in current distributions?

**Comment by SWW13** [comment]
The problem seems to be a typo in the source path:
`make[1]: *** /lid/modules/4.2.0-300.fc23.x86_64/build:` -> `/lid` instead of `/lib`

I don't know, possibly in some weeks.

**Comment by netzgestaltung** [comment]
the typo was mine by typing from tablet to pc...

i did another try and got another error message about gcc ist missing

so i installed gcc - whatever that is ... and it worked to install!

but the keyboard still doesnt work :( - i think it can be because thats a newer model?

thx for your patience!
