### ISSUE TITLE
Getting it into kernel

### ISSUE THREAD

**Issue by arty-name** [SWW13/hid-synaptics#7]
Hello. It looks like [there's no progress for the kernel patch](https://patchwork.kernel.org/patch/5737231/) and it's not in the latest kernel source. Would pinging developers help to put it through?

**Comment by SWW13** [comment]
Benjamin Tissoires created a improved patch (see http://www.spinics.net/lists/linux-input/msg40080.html) which is applied in upstream 4.3.

I hadn't time to check the new kernel, feel free to recheck the patch.

**Comment by arty-name** [comment]
That's good news! Thanks!
