### ISSUE TITLE
driver don't work with the 4.4 kernel for me

### ISSUE THREAD

**Issue by flutterbrony** [SWW13/hid-synaptics#8]
I can't compile it with Linux 4.4 on Ubtuntu 15.10, i get :

> To run a command as administrator (user "root"), use "sudo <command>".
> See "man sudo_root" for details.

```
ubuntu@ubuntu:/media/ubuntu/Data/hid/hid-acer-master$ make

make -C /lib/modules/4.4.0/build M=/media/ubuntu/Data/hid/hid-acer-master modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0'
  CC [M]  /media/ubuntu/Data/hid/hid-acer-master/hid-acer.o
./scripts/recordmcount: 1: ./scripts/recordmcount: Syntax error: end of file unexpected
scripts/Makefile.build:264: recipe for target '/media/ubuntu/Data/hid/hid-acer-master/hid-acer.o' failed
make[2]: *** [/media/ubuntu/Data/hid/hid-acer-master/hid-acer.o] Error 2
Makefile:1384: recipe for target '_module_/media/ubuntu/Data/hid/hid-acer-master' failed
make[1]: *** [_module_/media/ubuntu/Data/hid/hid-acer-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0'
Makefile:27: recipe for target 'default' failed
make: *** [default] Error 2
```

Can you please help me ?

**Comment by SWW13** [comment]
Since linux 4.3 there should be a working fix in the kernel. (see http://www.spinics.net/lists/linux-input/msg40080.html)

Have you tried the keyboard without this driver? If it's not working could you supply the `dmesg` output?

**Comment by flutterbrony** [comment]
[dmesg Ubuntu 15.10 4.4.txt](https://github.com/SWW13/hid-acer/files/107013/dmesg.Ubuntu.15.10.4.4.txt)

Here what dmesg return :

I have plug a usb keyboard to be more comfortable when typing command.
I need to clear the i2c read failed too, what I do when The keyboard and mouse work and I installe it on my Acer

**Comment by SWW13** [comment]
```
[    5.552698] hid-generic 0003:06CB:2968.0002: ignoring exceeding usage max
[    5.554167] input: ITE Tech. Inc. ITE Device(8595) as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.3/1-4.3:1.0/0003:06CB:2968.0002/input/input3
[    5.608820] hid-generic 0003:06CB:2968.0002: input,hiddev0,hidraw1: USB HID v1.10 Keyboard [ITE Tech. Inc. ITE Device(8595)] on usb-0000:00:14.0-4.3/input0
```

Looks like the upstream fix is working and the keyboard is recognized.
There should be no need for this driver.

Did a got that right that your keyboard is not working with untainted kernel?

**Comment by flutterbrony** [comment]
Yep and I don't know why, all seam to be correct

**Comment by flutterbrony** [comment]
After all, sometimes, the keyboard work. But only for some seconds, and it doesn't work again ...

**Comment by SWW13** [comment]
Then it's definitely not the rdesc bug and my driver workaround (and also the workaround in linux 4.3+) won't fix your problem.
I'm not deep into linux drivers so I have no glue what your problem could be.

I'm closing this issue because there is no reason for supporting linux 4.3+ and your problem is as far as i can tell not related to the fix the driver provides.
