### ISSUE TITLE
How to compile this in Linux 4.0?

### ISSUE THREAD

**Issue by im-tem** [SWW13/hid-synaptics#9]
I'm need to compile this in Ubuntu 15.04 (Linux 4.0), but I'm got this
![2016-03-26 19 00 53](https://cloud.githubusercontent.com/assets/18075164/14061147/4940ed34-f392-11e5-96a6-002a88e9634f.png)

**Comment by egor21312** [comment]
I'm replace Switch 10 ID in script, and this is works!

**Comment by SWW13** [comment]
You're trying to compile `rtl8723as`.

This is the `hid-acer` module.
